SteamWebApp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SteamWebApp.BLL.Entity.Abstract;
using SteamWebApp.Entities.Entity.Concrete;
using SteamWebApp.UI.Models.DTO;
using SteamWebApp.UI.Models.VM;

namespace SteamWebApp.UI.Controllers
{
    public class HomeController : Controller
    {
        private UserManager<User> _userManager;
        private IGameService _gameService;
        private ICommentService _commentService;
        public HomeController(IGameService gameService, UserManager<User> userManager, ICommentService commentService)
        {
            _gameService = gameService;
            _userManager = userManager;
            _commentService = commentService;
        }
        public IActionResult Index()
        {
            return View(new GameListVM()
            {
                Games = _gameService.GetAllByCategories()
            });
        }
        public IActionResult List(string category,int page = 1)
        {
            const int pageSize = 3;
            
            return View(new GameListVM() { 
                PageInfo = new PageInfo() { 
                    TotalItems = _gameService.GetCountByCategory(category),
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    CurrentCategory = category
                },
                Games = _gameService.GetGamesByCategory(category, page ,pageSize)
            });
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {

            
            Game game = _gameService.GetGameDetails((int)id);
            Game userGame = _gameService.GetGameDetailsByUser((int)id);
            
            if (game == null)
            {
                return NotFound();
            }

            if (User.Identity.IsAuthenticated)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                foreach (var item in userGame.GameUsers)
                {
                    if (user.Id == item.UserId)
                    {
                        GameDetailsVM model = new GameDetailsVM()
                        {
                            Game = game,
                            Categories = game.CategoryGames.Select(x => x.Category).ToList(),
                            GameUsers = userGame.GameUsers.Where(x => x.GameId == id).ToList(),
                            userId = user.Id
                        };
                        return View(model);
                    }
                }
                    GameDetailsVM modelNull = new GameDetailsVM()
                    {
                        Game = game,
                        Categories = game.CategoryGames.Select(x => x.Category).ToList(),
                        GameUsers = userGame.GameUsers.Where(x => x.GameId == id).ToList(),
                        userId = null
                    };
                    return View(modelNull);

                }
            else
            {
                return View(new GameDetailsVM()
                {
                    Game = game,
                    Categories = game.CategoryGames.Select(x => x.Category).ToList(),
                });
            }
            }



        }
        
    }
}

SteamWebApp.UI/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SteamWebApp.BLL.Entity.Abstract;
using SteamWebApp.Entities.Entity.Concrete;
using SteamWebApp.UI.Models.VM;

namespace SteamWebApp.UI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;
        private IGameUserService _gameUserService;
        private IGameService _gameService;
        private ICommentService _commentService;
        public UserController(UserManager<User> userManager, SignInManager<User> signInManager, IGameUserService gameUserService,IGameService gameService, ICommentService commentService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _gameUserService = gameUserService;
            _gameService = gameService;
            _commentService = commentService;
        }
        
        [HttpPost]
        public async Task<IActionResult> AddToLibrary(string userName,int gameId)
        {
            
            User user = await _userManager.FindByNameAsync(userName);
            var userId = user.Id;
            GameUser entity = new GameUser()
            {
                GameId = gameId,
                UserId = userId
            };
            _gameUserService.Add(entity);

            return Redirect("/Home/Details/"+gameId);
        }
        public async Task<IActionResult> GameList()
        {
            
            if (User.Identity.IsAuthenticated)
            {
                User user = await _userManager.FindByNameAsync(User.Identity.Name);
                User entity = _gameUserService.GetLibraryForUser(user.Id);
                return View(entity);

            }
            else
            {
                return Redirect("~/");
            }
            
        }
        [HttpPost]
        public IActionResult DeleteGameForUser(string userId, int gameId)
        {
            _gameUserService.DeleteFromLibrary(userId, gameId);
            return Redirect("/user/gamelist/");
        }

        [HttpPost]
        public async Task<IActionResult> submitComment(int gameId, string userName, string content)
        {
            User user = await _userManager.FindByNameAsync(userName);
            Game game = _gameService.GetById(gameId);
            Comment entity = new Comment()
            {
                Content = content,
                GameId = gameId,
                User = user,
                Game = game,

            };
            _commentService.Add(entity);
            return Redirect("/Home/Details/"+gameId);
        }
        [HttpPost]
        public IActionResult DeleteComment(int gameId,int commentId)
        {
            Comment comment = _commentService.GetById(commentId);
            _commentService.Delete(comment);
            return Redirect("/Home/Details/"+gameId);
        }


    }
}

SteamWebApp.UI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SteamWebApp.BLL.Entity.Abstract;
using SteamWebApp.UI.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SteamWebApp.UI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            return View(new CategoryListVM
            {
                SelectedCategory = RouteData.Values["category"]?.ToString(),
                Categories = _categoryService.GetAll()
            });
        }
    }
}

SteamWebApp.UI/ViewComponents/CommentViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SteamWebApp.BLL.Entity.Abstract;
using SteamWebApp.Entities.Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SteamWebApp.UI.ViewComponents
{
    public class CommentViewComponent:ViewComponent
    {
        private ICommentService _commentService;
        private UserManager<User> _userManager;
        public CommentViewComponent(ICommentService commentService, UserManager<User> userManager)
        {
            _commentService = commentService;
            _userManager = userManager;
        }
        public IViewComponentResult Invoke(int gameId)
        {

            List<Comment> model = _commentService.GetCommentWithUser(gameId);
            

            return View(model);
        }
    }
}

SteamWebApp.UI/Views/Home/Details.cshtml
@model GameDetailsVM
@{
    ViewData["Title"] = "Details";
}
<style>
    img.DetailsImg {
    float: left;
    position: relative;
    width: 100%;
}
    h4.FiyatSettings {
        width: auto;
        float: left;
        position: relative;
        color:cornflowerblue;
        margin-top:4px;
        margin-right:15px;
    }
    .FiyatButton {
    float: right;
    width: auto;
    position: relative;
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <img class="DetailsImg img-fluid" src="~/img/@Model.Game.Image" alt="@Model.Game.Name"/>
        </div>
        <div class="col-md-9">
            <h1>Game Name</h1>
            <h4 class="mb-3">
                @Model.Game.Name
            </h4>
            <hr />
            <h4>Categories</h4>
            @foreach (var item in Model.Categories)
            {
                <a asp-controller="Home" asp-action="List" asp-route-category="@item.Name.ToLower()" class="btn btn-link p-0 mb-3">
                    @item.Name |
                </a>

            }

            <div class="mb-3">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Description</h4>
                        <p class="">
                            @Html.Raw(Model.Game.Description)
                        </p>
                    </div>
                </div>
            </div>
            <div class="FiyatButton">

                @if (Model.Game.Price == 0)
                {
                    <h4 class="FiyatSettings">
                        Free Game
                    </h4>
                }
                else
                {

                    <h4 class="FiyatSettings">
                        @Model.Game.Price TL
                    </h4>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    if (Model.userId == null)
                    {
                        <form asp-controller="User" asp-action="AddToLibrary" method="post">
                            <input type="hidden" name="gameId" value="@Model.Game.Id" />
                            <input type="hidden" name="userName" value="@User.Identity.Name" />
                            <button type="submit" class="btn btn-primary btn-lg">Add To Library</button>
                        </form>
                    }
                    else
                    {
                        <h4>You Have</h4>
                    }

                }
                else
                {
                    <h4>login to buy </h4>
                }
            </div>
            <div>
                @await Component.InvokeAsync("Comment", new { gameId = Model.Game.Id })
            </div>
            @if (User.Identity.IsAuthenticated)
            {
        <form asp-controller="User" asp-action="submitComment" method="post">

            <div class="form-group row">
                <label asp-for="Content" class="col-md-2 col-form-label">Description</label>
                <div class="col-md-10">
                    <textarea class="form-control" id="editor" asp-for="Content" required=""></textarea>
                    <span asp-validation-for="Content"></span>
                </div>
            </div>
            <input type="hidden" name="gameId" value="@Model.Game.Id" />
            <input type="hidden" name="userName" value="@User.Identity.Name" />
            <button type="submit" class="btn btn-primary btn-lg">Submit Comment</button>
        </form>
            }


        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
   $('.btn').click(function(){
        if ($('#editor').val() == ""){
            alert('Please complete the field');

        }
    });
});
</script>

SteamWebApp.UI/Views/Home/Index.cshtml
@model GameListVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <div class="row">

        <div class="col-md-3">
            @await Component.InvokeAsync("CategoryList")
        </div>
        <div class="col-md-9">
            <div class="row">
                @foreach (var item in Model.Games)
                {
                    <partial name="_Game" for="@item" />
                }
            </div>
        </div>
    </div>

SteamWebApp.UI/Views/Home/List.cshtml
@model GameListVM
@{
    ViewData["Title"] = "List";
}


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryList")
    </div>

    <div class="col-md-9">

        <div class="row">
            @foreach (var item in Model.Games)
            {
                <partial name="_Game" for="@item" />
            }
        </div>
        <div page-model="@Model.PageInfo"></div>
    </div>
</div>